#ifndef __PARAMMODEL_H__
#define __PARAMMODEL_H__

enum MOTION_DETECT_PARAM
{
    MD_ENABLE,
    MD_SENSITIVITY,
    MD_MIN_SECONDS,
    MD_SAVE_CAPTURE,
    MD_SHOW_MOTION,
    MD_NIGHT_SWITCH,
    MD_MAX,
};

enum STORAGE_PARAM
{
    STORAGE_AUTO_UPLOAD,
    STORAGE_AUTO_DELETE,
    STORAGE_MAX,
};

enum RTSP_SERVER_PARAM
{
    RTSP_SERVER_ENABLE,
    RTSP_SERVER_USER,
    RTSP_SERVER_PASSWORD,
    RTSP_SERVER_PORT,
    RTSP_SERVER_MAX,
};

enum CONFIG_MODULE
{
    CONFIG_MOTION,
    CONFIG_STORAGE,
    CONFIG_RTSP_SERVER,
    CONFIG_MAX,
};

#endif